version: 0.2
phases:
  pre_build:
    commands:
      - GO111MODULE=on
  build:
    commands:
      - go mod download
      - go build .
      - aws cloudformation package --template-file template.yml --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - authorizer
    - template.yml
    - outputtemplate.yml