AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authorizer
Resources:
  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app
      Runtime: go1.x
      CodeUri: ./
      Environment:
        AWS_DB_REGION: "eu-west-2"
        AWS_DB_ENDPOINT: "https://dynamodb.eu-west-2.amazonaws.com"
        AWS_DB_TABLE: "authKeys"
        AUTH_HEADER: "X-Authorization"
        AUTH_PREFIX: "carprk"
  DataStore:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "key"
          AttributeType: "S"
      TableName: "authKeys"
      KeySchema:
        - AttributeName: "key"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5