name: Pull Request
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - name: lint
        run: $(go env GOPATH)/bin/golangci-lint run

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: dynamodb docker
        run: docker pull amazon/dynamodb-local
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: install test dependencies
        run: |
          pip install wheel setuptools --upgrade
          pip install awscli-local --upgrade
          docker run -p 4569:8000 -d amazon/dynamodb-local
      - name: create database
        run: ./cloud.sh testDatabase
      - name: run tests
        env:
          DB_TABLE: authorizer-dynamo-dev
          DB_REGION: eu-west-2
          DB_ENDPOINT: http://0.0.0.0:4569
        run: ./cloud.sh testCode

  automerge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/dependabot-auto-merge-action@v1.0.11
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
